#include<stdio.h>
int main()
{
    int a[100],i,j,b[100],n,m,c=0,l=0;
    scanf("%d",&n);
    scanf("%d",&m);
    for(i=0;i<n;i++)
    {
        scanf("%d",&a[i]);
    }
    for(j=0;j<m;j++)
    {
        scanf("%d",&b[j]);
    }
    for(j=0;j<m;j++)
    {
        l++;
    }
    for(i=0;i<n;i++)
    {
        for(j=0;j<m;j++)
        {
            if(a[i]==b[j])
            {
                c++;
            }
        }
    }
    if(c==l)
    printf("YES");
    else
    printf("NO");
}
